version: "3"

services:
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    labels: 
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`localhost`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: 3000
      
  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/app:/code/app 
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - REDIRECT_URI=
    labels: 
      traefik.enable: true
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api/v1`)
      traefik.http.services.backend.loadbalancer.server.port: 80
      traefik.http.middlewares.backendpathstrip.stripprefix.prefixes: /api/v1
      traefik.http.routers.backend.middlewares: backendpathstrip@docker