version: "3"

services:
  traefik:
    image: traefik:v2.4
    container_name: your-spotify-monthly-traefik-dev
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    container_name: your-spotify-monthly-app-dev
    build: 
      context: ./app
      target: development
    volumes:
      - ./app:/usr/src/app
      - your_spotify_node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    labels: 
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`localhost`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: 3000

  redis:
    container_name: your-spotify-monthly-redis-dev
    image: redis

volumes:
  your_spotify_node_modules: